<?php
require_once('web/testing.php');
require_once('web/local.php');
require_once('web/auth.php');
require_once('web/backend.php');
require_once('web/frontend.php');
/*require_once('web/.php');
require_once('web/.php');
require_once('web/.php');
require_once('web/.php');
require_once('web/.php');*/
